config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'public#index'

  get 'public/index'

  get 'login', :to => 'access#login'

  get 'access/login'

  get 'access/attempt_login'
  post 'access/attempt_login'

  get 'access/logout'

  get 'addmoney', to: 'envelopes#edit_multiple'

  resources :envelopes do
    collection do
      get :edit_multiple
      put :update_multiple
    end
  end
  resources :users
  resources :transactions
  resources :add_money

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/envelope.rb
class Envelope < ApplicationRecord
  belongs_to :user
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :envelope

  scope :newest_first, lambda { order("date DESC") }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :envelopes
  has_many :transactions

  validates :username, uniqueness: true
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  layout 'public'

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      session[:username] = authorized_user.username
      flash[:notice] = "You are now logged in."
      redirect_to(envelopes_path)
    else
      flash.now[:notice] = "Ivalid username/password combination."
      render('login')
    end
  end

  def logout
    reset_session
    flash[:notice] = "Logged Out"
    redirect_to(login_path)
  end
end

app/controllers/add_money_controller.rb
class AddMoneyController < ApplicationController

  layout 'user'

  before_action :find_user

  def index
    @envelopes = @user.envelopes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def find_user
    @user = User.find(session[:user_id])
  end

end

app/controllers/envelopes_controller.rb
class EnvelopesController < ApplicationController

  layout 'user'

  before_action :find_user
  before_action :set_envelope, only: [:show, :edit, :update, :destroy]

  def index
    @envelopes = @user.envelopes
    @total = @envelopes.sum(:total)
  end

  def show
    @envelope = Envelope.find(params[:id])
    @transactions = @envelope.transactions
    # @envelope.total = @envelope.total - @transactions.sum(:amount)
  end

  def new
    @envelope = Envelope.new
  end

  def edit
    @envelope = Envelope.find(params[:id])
  end

  def edit_multiple
    @envelopes = @user.envelopes
  end

  def create
    @envelope = Envelope.new(envelope_params)
    @envelope.user = @user
    @envelope.total = 0
    @envelope.initialTotal = 0 if @envelope.initialTotal.nil?
    if @envelope.save
      redirect_to envelopes_path
      flash[:notice] = 'Envelope succesfully added'
    else
      render :new
    end
  end

  def update
    if @envelope.update(envelope_params)
      redirect_to envelopes_path
      flash[:notice] = 'Envelope updated succesfully'
    else
      render :edit
    end
  end

  def update_multiple
    params[:envelopes].each_pair do |k, v|
      envelope = Envelope.find(k)
      envelope.total += v['total'].to_i
      envelope.save
    end
    redirect_to envelopes_path
  end

  def destroy
    @envelope.transactions.destroy_all
    @envelope.destroy
    flash[:notice] = 'Envelope succesfully deleted'
    redirect_to envelopes_path
  end

  private

  def set_envelope
      @envelope = Envelope.find(params[:id])
      if @envelope.user_id != session[:user_id]
        redirect_to login_path
        flash[:notice] = "Access Denied. Enevelope does not belong to you"
      end
  end

  def envelope_params
    params.require(:envelope).permit(:name, :initialTotal, :total)
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  layout 'public'

  def index
  end
  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  layout 'user'

  before_action :set_transaction, only: [:edit, :update, :destroy]
  before_action :find_user

  def index
    @transactions = @user.transactions.newest_first
  end

  def new
    @transaction = Transaction.new
    @envelopes = @user.envelopes
    @transaction.envelope_id = params[:envelope_id]
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = @user
    @envelope = Envelope.find(transaction_params[:envelope_id])
    @transaction.envelope_name = @envelope.name
    @envelope.total -= @transaction.amount

    if @transaction.save && @envelope.save
      redirect_to envelope_path(@envelope)
      flash[:notice] = 'Transaction succesfully added'
    else
      render :new
    end
  end

  def edit
    @envelopes = @user.envelopes
  end

  def update
    @envelope = @transaction.envelope
    print(@envelope.id)
    if @envelope.id != transaction_params[:envelope_id].to_f
      @envelope.total = (@envelope.total + @transaction.amount)
      @new_envelope = Envelope.find(transaction_params[:envelope_id])
      @new_envelope.total -= transaction_params[:amount].to_f
      @transaction.envelope_name = @new_envelope.name
      @new_envelope.save
    else
    @envelope.total = ((@envelope.total + @transaction.amount) - transaction_params[:amount].to_f)
    end
    if @transaction.update(transaction_params) && @envelope.save
      redirect_to envelopes_path
      flash[:notice] = 'Envelope updated succesfully'
    else
      render :edit
    end
  end

  def destroy
    @envelope = @transaction.envelope
    @envelope.total += @transaction.amount
    if @envelope.save && @transaction.destroy
      flash[:notice] = "Transaction succesfully deleted"
      redirect_to(transactions_path)
    end
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:envelope_id, :name, :amount, :date)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout 'user', except: [:new]
  layout 'public'

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
      flash[:notice] = 'Account was succesfully created'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path
      flash[:notice] = 'Info updated succesfully'
    else
      render :edit
    end
  end

  def destroy

  end

  private

  def set_user
    @user = User.find(session[:user_id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :username, :password)
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/add_money_helper.rb
module AddMoneyHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/envelopes_helper.rb
module EnvelopesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/login.html.erb
<div class="login">
  <h1 class="text-center"><%= @page_title = "Login" %></h>
  <%= form_tag(access_attempt_login_path, :method => :post, class: 'form-signin') do %>
    <%= label_tag(:username, nil, class: 'sr-only') %>
    <%= text_field_tag(:username, params[:username], class: "form-control", placeholder: "Username") %>
    <%= label_tag(:password, nil, class: 'sr-only') %>
    <%= password_field_tag(:password, nil, class: 'form-control', placeholder: 'Password' ) %>
    &nbsp;
    <%= submit_tag("Log In", class: 'btn btn-primary btn-block') %>
  <% end %>
</div>

app/views/add_money/index.html.erb
<div class="container">
  <h1 class="text-center"><%= @page_title = "Add Money" %></h1>

  <%= form_tag add_money_path do %>
  <% @envelope.each do |envelope| %>
    <%= fields_for 'envelopes[]', envelope do |p| %>

      <div class="field">
        <%= p.label :name %><br>
        <%= p.text_field :name %>
      </div>
      <div class="field">
        <%= p.label :amount %><br>
        <%= p.number_field(:amount, class: 'form-control',step: :any, placeholder: 'Amount') %>
      </div>

    <% end %>
  <% end %>
  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

  <ul>
    <% @envelopes.each do |e| %>
    <li><%= e.name %></li>
    <% end %>
  </ul>


</div>

app/views/envelopes/_form.html.erb
<%= form_for(envelope, :url => envelopes_path) do |f| %>
<% if envelope.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(envelope.errors.count, "error") %> prohibited this envelope from being saved:</h2>

  <ul>
    <% envelope.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= label_tag(:name, 'name', class: 'sr-only') %>
<%= f.text_field(:name, class: 'form-control', placeholder: 'Name') %>

<%= label_tag(:initotal, 'Budgeted Amount', class: 'sr-only') %>
<div class="input-group">
  <div class="input-group-prepend">
      <div class="input-group-text">$</div>
    </div>
  <%= f.number_field(:initialTotal, class: 'form-control', placeholder: 'Bugeted Amount') %>
</div>


<br>
<%= f.submit "Create", class: "btn btn-primary btn-block" %>


<% end %>

app/views/envelopes/edit.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead">Edit Envelope:</p>
    <h1 class="display-3"><%= @page_title = "#{@envelope.name}" %></h1>
  </div>
</div>
<div class="container">
  <div class="form-signin">
    <% envelope = @envelope %>
    <%= form_for(envelope, :url => envelope_path) do |f| %>
    <% if envelope.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(envelope.errors.count, "error") %> prohibited this envelope from being saved:</h2>

      <ul>
        <% envelope.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= label_tag(:name, 'Name') %>
    <%= f.text_field(:name, class: 'form-control', placeholder: 'Name') %>

    <%= label_tag(:initialTotal, 'Budgeted Amount') %>
    <div class="input-group">
      <div class="input-group-prepend">
        <div class="input-group-text">$</div>
      </div>
      <%= f.number_field(:initialTotal, class: 'form-control', step: :any, placeholder: 'Budgeted Amount') %>
    </div>


    <%= label_tag(:total, 'Envelope Balance') %>
    <div class="input-group">
      <div class="input-group-prepend">
        <div class="input-group-text">$</div>
      </div>
      <%= f.number_field(:total, class: 'form-control', placeholder: 'Envelope Balance') %>
    </div>
    <br>
    <%= f.submit "Update", class: "btn btn-primary btn-block" %>
    <% end %>
    <br>
    <%= link_to 'Delete', envelope_path(@envelope), class: "btn btn-outline-danger btn-block", method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/envelopes/edit_multiple.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead">Edit:</p>
    <h1 class="display-3"><%= @page_title = "Add Money" %></h1>
  </div>
</div>
<div class="container">
  <div class="form-signin">
    <label for="total">Total</label>
    <div class="input-group">
      <div class="input-group-prepend">
        <div class="input-group-text">$</div>
      </div>
      <input id="total" type="number" name="total" value="0" class="form-control">
    </div>
    <br>
    <h4>Unallocated: <span id="unallocated"></span></h4>
  </div>
  <h3 class="text-center">Envelopes</h3>
  <div class="form-signin">
    <%= form_tag update_multiple_envelopes_path, method: :put, id: 'inputs' do %>
      <% @envelopes.each do |envelope| %>
        <%= fields_for 'envelopes[]', envelope do |p| %>
            <%= p.label envelope.name %>
            <span>Budgeted amount: $<%= envelope.initialTotal %></span>
            <div class="input-group">
              <div class="input-group-prepend">
                <div class="input-group-text">$</div>
              </div>
              <%= p.number_field(:total, class: 'form-control',step: :any, placeholder: 'Amount', value: envelope.initialTotal) %>
            </div>

        <% end %>
      <% end %>
      <br>
      <%= submit_tag 'Add Money', class: "btn btn-primary btn-block", id: 'submit', disabled: true %>
    <% end %>
  </div>
</div>

app/views/envelopes/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead">Balance:</p>
    <h1 class="display-3">$<%= @total %></h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-12 ml-auto">
      <div class="btn-group float-right">
        <%= link_to "+ Transaction", new_transaction_path, class: "btn btn-primary" %>
        <%= link_to "+ Money", addmoney_path, class: "btn btn-primary" %>
        <%= link_to "+ Envelope", new_envelope_path, class: 'btn btn-primary' %>
      </div>

    </div>
  </div>
  <h1 class="text-center"><%= @page_title = "Envelopes" %></h1>
  <div class="row">
    <table class="table table-hover table-sm">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Money Availible</th>
        </tr>
      </thead>
      <tbody>
        <% @envelopes.each do |envelope| %>
          <tr class="clickable-row" data-href='<%= envelope_path(envelope)%>'>
            <td><%= envelope.name %></td>
            <td><span class="card-text <% if envelope.total <= 0 %>red<% end %>">$<%= envelope.total %></span><span> of $<%= envelope.initialTotal %></span><div class="progress">
              <div class="progress-bar" role="progressbar" style="width: <%= envelope.total/envelope.initialTotal * 100 %>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/envelopes/new.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead">View:</p>
    <h1 class="display-3"><%= @page_title = "Create Envelope" %></h1>
  </div>
</div>
<div class="container">
  <div class="form-signin">
    <%= render 'form', envelope: @envelope %>
  </div>
</div>

app/views/envelopes/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead"><%= @envelope.name %> Balance:</p>
    <h1 class="display-3 <% if @envelope.total <= 0 %>red<% end %>">$<%= @envelope.total %></h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="btn-group float-right" role="group" aria-label="Basic example">
        <%= link_to "+ Transaction", new_transaction_path(envelope_id: @envelope.id), class: "btn btn-primary" %>
        <%= link_to "Edit", edit_envelope_path(@envelope), class: "btn btn-primary" %>
      </div>
    </div>
  </div>

    <h2 class="text-center"><%= @envelope.name %> Transactions</h2>
    <div class="row">
      <div class="col-sm-12">
        <table class="table table-sm table-striped">
          <thead class="thead-default">
            <tr>
              <th>Date</th>
              <th>Name</th>
              <th>Amount</th>
              <th>Options</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <% @transactions.each do |t| %>
              <tr>
                <td><%= t.date %></td>
                <td><%= t.name %></td>
                <td>-$<%= t.amount %></td>
                <td><%= link_to "Edit", edit_transaction_path(t), class: "btn btn-primary btn-sm" %></td>
              </tr>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BudgetApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-dark navbar-expand-md">
      <a class="navbar-brand" href="#">
        <%= image_tag 'mail.png' %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <span><%= link_to("Sign Up", new_user_path, :class => 'btn btn-outline-info my-2 my-sm-0') %></span><span> |</span>

          <%= link_to("Login", access_login_path, :class => 'btn btn-outline-info my-2 my-sm-0') %>
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>BudgetApp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div id="container">
    <div id="main">
      <nav class="navbar fixed-top navbar-dark navbar-expand-md">
          <%= link_to(envelopes_path, class: 'navbar-brand') do %>
          <%= image_tag 'mail.png' %>
          <%= @user.name %>
          <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <% if @page_title == 'Envelopes' %>active<% end %>">
              <%= link_to("Envelopes", envelopes_path, class: 'nav-link') %>
            </li>
            <li class="nav-item <% if @page_title == 'All Transactions' %>active<% end %>">
              <%= link_to("Transactions", transactions_path, class: 'nav-link') %>
            </li>
            <li class="nav-item <% if @page_title == 'Add Money' %>active<% end %>">
              <%= link_to("+ Money", addmoney_path, class: 'nav-link') %>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <%= link_to("Logout", access_logout_path, class: 'btn btn-outline-info my-2 my-sm-0') %>
          </form>
        </div>
      </nav>
      <%= yield %>
    </div>
    <footer class="bg-dark">
      <div class="container">
        Sealed Budget
      </div>
    </footer>
  </div>
</body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(transaction, :url => transactions_path) do |f| %>
<% if transaction.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

  <ul>
    <% transaction.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= f.label(:envelope_id, 'Envelope') %>
<%= f.collection_select(:envelope_id, @envelopes, :id, :name,{}, {class: 'form-control'}) %>

<%= label_tag(:name, 'name', class: 'sr-only') %>
<%= f.text_field(:name, class: 'form-control', placeholder: 'Payee') %>

<%= label_tag(:amount, 'total', class: 'sr-only') %>
<div class="input-group">
  <div class="input-group-prepend">
    <div class="input-group-text">$</div>
  </div>
<%= f.number_field(:amount, class: 'form-control',step: :any, placeholder: 'Amount') %>
</div>

<%= label_tag(:date, 'total', class: 'sr-only') %>
<%= f.date_field(:date, value: Date.today, class: 'form-control',step: :any, placeholder: 'Date') %>
<br>
<%= f.submit "Create", class: "btn btn-primary btn-block" %>


<% end %>

app/views/transactions/edit.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead">Edit Transaction:</p>
    <h1 class="display-3"><%= @page_title = "#{@transaction.name}" %></h1>
  </div>
</div>
<div class="container">
  <div class="form-signin">
    <% transaction = @transaction %>
    <%= form_for(transaction, :url => transaction_path) do |f| %>
    <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <%= label_tag(:envelope_id, 'Envelope') %>
    <%= f.collection_select(:envelope_id, @envelopes, :id, :name,{}, class: 'form-control') %>

    <%= label_tag(:name, ' Transaction Name') %>
    <%= f.text_field(:name, class: 'form-control', placeholder: ' Transaction Name') %>

    <%= label_tag(:amount, 'Amount') %>
    <div class="input-group">
      <div class="input-group-prepend">
        <div class="input-group-text">$</div>
      </div>
    <%= f.number_field(:amount, class: 'form-control',step: :any, placeholder: 'Amount') %>
    </div>

    <%= label_tag(:date, 'Date') %>
    <%= f.date_field(:date, class: 'form-control',step: :any, placeholder: 'Date') %>

    <br>
    <%= f.submit "Update", class: "btn btn-primary btn-block" %>
    <br>
    <%= link_to 'Delete', transaction_path(transaction), class: "btn btn-outline-danger btn-block", method: :delete, data: { confirm: 'Are you sure?' } %>


    <% end %>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead">View:</p>
    <h1 class="display-3"><%= @page_title = "All Transactions" %></h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <table class="table table-sm table-striped">
      <thead class="thead-default">
        <tr>
          <th>Date</th>
          <th>Name</th>
          <th>Envelope</th>
          <th>Amount</th>
          <th>Options</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% @transactions.each do |t| %>
          <tr>
            <td><%= t.date %></td>
            <td><%= t.name %></td>
            <td><%= t.envelope_name %></td>
            <td>-$<%= t.amount %></td>
            <td>
              <%= link_to "Edit", edit_transaction_path(t), class: "btn btn-primary btn-sm" %>
            </td>
          </tr>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead">View:</p>
    <h1 class="display-3"><%= @page_title = "Create Transaction" %></h1>
  </div>
</div>
<div class="container">
  <div class="form-signin">
    <%= render 'form', transaction: @transaction %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(user, :url => users_path) do |f| %>
<% if user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= label_tag(:name, 'name', class: 'sr-only') %>
<%= f.text_field(:name, class: 'form-control', placeholder: 'Name') %>

<%= label_tag(:email, 'email', class: 'sr-only') %>
<%= f.email_field(:email, class: 'form-control', placeholder: 'Email') %>

<%= label_tag(:username, 'username', class: 'sr-only') %>
<%= f.text_field(:username, class: 'form-control', placeholder: 'Username') %>

<%= label_tag(:password, 'password', class: 'sr-only') %>
<%= f.password_field(:password, class: 'form-control', placeholder: 'Password') %>
<br>
<%= f.submit "Sign Up", class: "btn btn-primary btn-block" %>


<% end %>

app/views/users/new.html.erb
<div class="container">
  <h1 class="text-center">Sign Up</h1>
  <%= render 'form', user: @user %>
</div>